// <auto-generated />
using Lab5_Jermaine.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lab5_Jermaine.Migrations
{
    [DbContext(typeof(playerContext))]
    [Migration("20201206025619_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Lab5_Jermaine.Models.Players", b =>
                {
                    b.Property<string>("playerName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("playerCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("playerNumber")
                        .HasColumnType("int");

                    b.Property<string>("playerPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("playerTeam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("playerName");

                    b.ToTable("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
